// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBonEooLtFCQdV0CtNlAa1XjAhjkvBzZCg',
    appId: '1:773444533567:web:32f9b25a7c003b11ec278a',
    messagingSenderId: '773444533567',
    projectId: 'homepage-28afc',
    authDomain: 'homepage-28afc.firebaseapp.com',
    storageBucket: 'homepage-28afc.appspot.com',
    measurementId: 'G-VWZWE6CHYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLs05QZV-L8hMckbiHQB89FDN7tJv0ZdQ',
    appId: '1:773444533567:android:76b8424a295a10feec278a',
    messagingSenderId: '773444533567',
    projectId: 'homepage-28afc',
    storageBucket: 'homepage-28afc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLBsJ8VKqKGrUXMClSOA3gzclNWjuSVLQ',
    appId: '1:773444533567:ios:58e449ff0b1722dcec278a',
    messagingSenderId: '773444533567',
    projectId: 'homepage-28afc',
    storageBucket: 'homepage-28afc.appspot.com',
    iosBundleId: 'com.example.homePage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLBsJ8VKqKGrUXMClSOA3gzclNWjuSVLQ',
    appId: '1:773444533567:ios:f5c0ab7be9d83053ec278a',
    messagingSenderId: '773444533567',
    projectId: 'homepage-28afc',
    storageBucket: 'homepage-28afc.appspot.com',
    iosBundleId: 'com.example.homePage.RunnerTests',
  );
}
